# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run tests with pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-20.04']
        python-version: ['3.12']

    runs-on: ${{ matrix.os-version }}
    name: unittests with py-${{ matrix.python-version }} on ${{ matrix.os-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: test task_1 with pytest
      run: pytest task_1/test_solve.py
    - name: test task_2 with pytest
      run: pytest task_2/test_solve.py
    - name: test task_3 with pytest
      run: pytest task_3/test.py
